# Generated by Django 2.1.1 on 2020-07-10 03:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('content', '0005_auto_20200710_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='write_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
