# Generated by Django 2.1.1 on 2020-07-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200709_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
