# Generated by Django 2.1.1 on 2020-07-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200710_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user_id',
        ),
    ]
