# Generated by Django 2.1.1 on 2020-07-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_todolist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='write_time',
        ),
    ]
