# Generated by Django 2.1.1 on 2020-07-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200710_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='user_id',
        ),
    ]
